# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'AFIExercise.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET Core SDK
  inputs:
    packageType: 'sdk'
    version: 3.1.402
- task: DotNetCoreCLI@2
  displayName: Build .NET Code
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) /p:Platform=$(buildPlatform)'

- task: DotNetCoreCLI@2
  displayName: Test .NET Code
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) /p:Platform=$(buildPlatform)'