# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'AFIExercise.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET Core SDK
  inputs:
    packageType: 'sdk'
    version: 3.1.402
- task: DotNetCoreCLI@2
  displayName: Build .NET Code
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test .NET Code
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  env:
    ConnectionStrings:SqlServer: $(ConnectionStrings:SqlServer)
- task: DotNetCoreCLI@2
  displayName: Publish Web App
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: Publish build artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'afi-exercise-web-api'
- task: AzureWebApp@1
  displayName: Deploy to Azure
  inputs:
    azureSubscription: 'Visual Studio Enterprise(473b619f-ab83-4122-9e70-726780c0c243)'
    appType: 'webAppLinux'
    appName: 'afi-exercise-web-api'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'